---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mytbedge
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize/edge
  prune: true
  sourceRef:
    kind: GitRepository
    name: mytbedge
  targetNamespace: regiona
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: geol
            operator: In
            values:
            - regiona
  patches:
    - patch: |-
        apiVersion: autoscaling/v2beta2
        kind: HorizontalPodAutoscaler
        metadata:
          name: mytbedge
        spec:
          minReplicas: 1
      target:
        name: podinfo
        kind: HorizontalPodAutoscaler
