---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mytbedge
  namespace: regiona
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/lillianphyo/tb_edge_deploy

